language: csharp
sudo: required
os:
  - linux
  - osx
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-get --ignore-missing install libunwind-dev gettext; fi
script:
  - ./build.sh --quiet verify